#!/usr/bin/env bash

function display() {
	echo -en "travis_fold:start:$1\r\033[0K"
}

if [[ "$1" =~ -.+ ]]; then
	display $(echo $1 | sed 's/^\-//')
	exit
fi

name="custom_fold"
display start
[ -z $1 ] || echo $*
cat
display end
